[tox]

envlist =
    mypy
    ruff
    codespell

[testenv:mypy]
deps =
    mypy ~= 2.1.0

commands =
    mypy icc-brightness {posargs}

[testenv:ruff]
deps =
    ruff ~= 0.15.14

commands =
    ruff check icc-brightness {posargs}

[testenv:codespell]
deps = codespell ~= 2.4.2
commands =
    codespell --config=tox.ini icc-brightness README.md {posargs}
